server:
  port: 8082

spring:
  application:
    name: NoteApplication
  datasource:
    url: jdbc:h2:mem:noteApiDB
    driver-class-name: org.h2.Driver
    username: root
    password: root
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
